runtime: python27
entrypoint: gunicorn -b :$PORT main:app
threadsafe: true

handlers:
- url: /
  script: home.app
- url: /.*
  script: home.app

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 5
  max_instances: 100
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50